spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ecom-auth
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/ecomdb}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      platform: postgres
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
